// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSfUwsCJ5U-BH584qaYj_oRs6Ihz2dsI0',
    appId: '1:567487683137:web:f33853f41f7461f538c4c0',
    messagingSenderId: '567487683137',
    projectId: 'pages-and-pals',
    authDomain: 'pages-and-pals.firebaseapp.com',
    storageBucket: 'pages-and-pals.firebasestorage.app',
    measurementId: 'G-2752SWBHXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI_wtKdhu-pUw_2hGY9YL1BxJvR5ec6_8',
    appId: '1:567487683137:android:5988878f56264cd738c4c0',
    messagingSenderId: '567487683137',
    projectId: 'pages-and-pals',
    storageBucket: 'pages-and-pals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnPUw_3oyn7eH5zXK45XGpn4EFkvTdT5g',
    appId: '1:567487683137:ios:c825c22f3e70365938c4c0',
    messagingSenderId: '567487683137',
    projectId: 'pages-and-pals',
    storageBucket: 'pages-and-pals.firebasestorage.app',
    iosBundleId: 'com.example.pagesAndPals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnPUw_3oyn7eH5zXK45XGpn4EFkvTdT5g',
    appId: '1:567487683137:ios:c825c22f3e70365938c4c0',
    messagingSenderId: '567487683137',
    projectId: 'pages-and-pals',
    storageBucket: 'pages-and-pals.firebasestorage.app',
    iosBundleId: 'com.example.pagesAndPals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSfUwsCJ5U-BH584qaYj_oRs6Ihz2dsI0',
    appId: '1:567487683137:web:e9b191cfe4184a2138c4c0',
    messagingSenderId: '567487683137',
    projectId: 'pages-and-pals',
    authDomain: 'pages-and-pals.firebaseapp.com',
    storageBucket: 'pages-and-pals.firebasestorage.app',
    measurementId: 'G-WG8MSENFW7',
  );
}
